// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

namespace WebApi.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteDataContext))]
    [Migration("20201028182441_Parts")]
    partial class Parts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("WebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Entities.current_nav_equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("acc_depn_value")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("current_nav")
                        .HasColumnType("TEXT");

                    b.Property<string>("depreciation_ed_yrmth")
                        .HasColumnType("TEXT");

                    b.Property<string>("depreciation_st_yrmth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("depreciation_value")
                        .HasColumnType("TEXT");

                    b.Property<int>("depreciation_year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("current_nav_equipment");
                });

            modelBuilder.Entity("WebApi.Entities.equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cert_no")
                        .HasColumnType("TEXT");

                    b.Property<int?>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dt_acquisition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_cert")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dt_commissioning")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_deleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dt_installation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_modified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dt_site_delivery")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_warranty_exp")
                        .HasColumnType("TEXT");

                    b.Property<int>("equipment_model_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("equipment_no")
                        .HasColumnType("TEXT");

                    b.Property<int>("equipment_status_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("equipment_statusid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("horsepower")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("is_deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .HasColumnType("TEXT");

                    b.Property<string>("longitude")
                        .HasColumnType("TEXT");

                    b.Property<int>("media_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("mfg_year")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("modified_by")
                        .HasColumnType("INTEGER");

                    b.Property<string>("remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("sales_contact_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("sales_contact_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("serial_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("support_contact_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("support_contact_no")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("equipment_statusid");

                    b.ToTable("equipments");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_field", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("field_type")
                        .HasColumnType("TEXT");

                    b.Property<string>("field_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("equipment_field");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_file", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("file_type")
                        .HasColumnType("TEXT");

                    b.Property<int>("media_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("equipment_file");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_link", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("link")
                        .HasColumnType("TEXT");

                    b.Property<string>("link_type")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("equipment_link");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_model", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dt_created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_deleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("equipment_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("is_deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mfg_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("model_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("model_no")
                        .HasColumnType("TEXT");

                    b.Property<int?>("modified_by")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("process_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("sales_contact_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("sales_contact_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("support_contact_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("support_contact_no")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("equipment_model");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_model_field", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_model_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("field_type")
                        .HasColumnType("TEXT");

                    b.Property<string>("field_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("equipment_model_field");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_model_file", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_model_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("file_type")
                        .HasColumnType("TEXT");

                    b.Property<int>("media_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("equipment_model_file");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_model_link", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_model_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("link")
                        .HasColumnType("TEXT");

                    b.Property<string>("link_type")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("equipment_model_link");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_model_part", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_model_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("part_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("equipment_model_part");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_model_part_model", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_model_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("part_model_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("equipment_model_part_model");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_part", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipment_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("part_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("equipment_part");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("equipment_status");
                });

            modelBuilder.Entity("WebApi.Entities.equipment_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_modified")
                        .HasColumnType("TEXT");

                    b.Property<int?>("modified_by")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("equipment_type");
                });

            modelBuilder.Entity("WebApi.Entities.estimated_nav", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dt_created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dt_installation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_invoice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_modified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dt_obsolete")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dt_operation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dt_purchase")
                        .HasColumnType("TEXT");

                    b.Property<int>("equipment_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("invoice_no")
                        .HasColumnType("TEXT");

                    b.Property<int>("is_deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("modified_by")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("purchase_value")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("estimated_nav");
                });

            modelBuilder.Entity("WebApi.Entities.media", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dt_created")
                        .HasColumnType("TEXT");

                    b.Property<string>("file_name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("media");
                });

            modelBuilder.Entity("WebApi.Entities.part", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cert_no")
                        .HasColumnType("TEXT");

                    b.Property<int?>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dt_acquisition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_cert")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_deleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_installation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_modified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_warranty_exp")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("is_deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("media_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("mfg_year")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("modified_by")
                        .HasColumnType("INTEGER");

                    b.Property<int>("part_model_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("part_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("sales_contact_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("sales_contact_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("serial_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("support_contact_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("support_contact_no")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("parts");
                });

            modelBuilder.Entity("WebApi.Entities.part_model", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<int?>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dt_created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_deleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_modified")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("is_deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mfg_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("model_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("model_no")
                        .HasColumnType("TEXT");

                    b.Property<int?>("modified_by")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("part_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("sales_contact_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("sales_contact_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("support_contact_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("support_contact_no")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("part_model");
                });

            modelBuilder.Entity("WebApi.Entities.policy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("depreciation_rate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dt_modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("equipment_model_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("is_deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("life_span")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("modified_by")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("policies");
                });

            modelBuilder.Entity("WebApi.Entities.equipment", b =>
                {
                    b.HasOne("WebApi.Entities.equipment_status", "equipment_status")
                        .WithMany()
                        .HasForeignKey("equipment_statusid");
                });
#pragma warning restore 612, 618
        }
    }
}
